# 应用服务 WEB 访问端口
server:
  port: 8080

# spring配置
spring:
  application:
    name: spring-boot-captcha
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    # Redis服务器地址
    host: 10.10.62.67
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 3000ms
    # Redis的Java驱动包
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制），默认8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 (默认为8)
        max-idle: 8
        # 连接池中的最小空闲连接，默认0
        min-idle: 0

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.jourwon.spring.boot.*.entity
  global-config:
    db-config:
      # 数据库ID自增
      id-type: auto
  configuration:
    # 关闭Mybatis二级缓存
    cache-enabled: false
    # 设置sql执行超时时间,以秒为单位的全局sql超时时间设置,当超出了设置的超时时间时,会抛出SQLTimeoutException
    default-statement-timeout: 30
    # 解决查询返回结果含null没有对应字段值问题
    call-setters-on-nulls: true
    # 开启驼峰规则自动映射字段属性值;如字段为user_name的可以映射到userName属性中
    map-underscore-to-camel-case: true
    # 开发环境控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl