# Redis单机模式配置
spring:
  redis:
    # Redis服务器地址
    host: 47.119.113.228
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 3000ms
    # Redis的Java驱动包
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制），默认8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 (默认为8)
        max-idle: 8
        # 连接池中的最小空闲连接，默认0
        min-idle: 0

# Redis哨兵模式配置
#spring:
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器连接密码（默认为空）
#    password: 123456
#    # 连接超时时间（毫秒）
#    timeout: 3000ms
#    # 集群配置
#    sentinel:
#      # master服务名称
#      master: mymaster
#      # 哨兵节点
#      nodes: 47.119.113.228:26379,47.119.113.228:36379,47.119.113.228:46379
#      # 哨兵认证密码
#      password: 123456
#    # Redis的Java驱动包
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制），默认8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认-1
#        max-wait: -1
#        # 连接池中的最大空闲连接 (默认为8)
#        max-idle: 8
#        # 连接池中的最小空闲连接，默认0
#        min-idle: 0

# Redis集群模式配置
#spring:
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器连接密码（默认为空）
#    password: 123456
#    # 连接超时时间（毫秒）
#    timeout: 3000ms
#    # 集群配置
#    cluster:
#      # 集群节点
#      nodes: 47.119.113.228:7100,47.119.113.228:7200,47.119.113.228:7300,47.119.113.228:7400,47.119.113.228:7500,47.119.113.228:7600
#      # 最大重定向次数
#      max-redirects: 6
#    # Redis的Java驱动包
#    lettuce:
#      cluster:
#        refresh:
#          # 刷新redis集群的拓扑(默认是false)
#          adaptive: true
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制），默认8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认-1
#        max-wait: -1
#        # 连接池中的最大空闲连接 (默认为8)
#        max-idle: 8
#        # 连接池中的最小空闲连接，默认0
#        min-idle: 0
