# 应用服务 WEB 访问端口
server:
  port: 8080

# spring配置
spring:
  application:
    name: spring-boot-mybatis-plus
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 设置严格模式,默认false不启动,启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        slave:
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.jourwon.spring.boot.*.entity
  global-config:
    db-config:
      # 数据库ID自增
      id-type: auto
  configuration:
    # 关闭Mybatis二级缓存
    cache-enabled: false
    # 设置sql执行超时时间,以秒为单位的全局sql超时时间设置,当超出了设置的超时时间时,会抛出SQLTimeoutException
    default-statement-timeout: 30
    # 解决查询返回结果含null没有对应字段值问题
    call-setters-on-nulls: true
    # 开启驼峰规则自动映射字段属性值;如字段为user_name的可以映射到userName属性中
    map-underscore-to-camel-case: true
    # 开发环境控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl