# 应用服务 WEB 访问端口
server:
  port: 8080

# spring配置
spring:
  application:
    name: spring-boot-data-jpa
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    # 数据库类型
    database: MYSQL
    database-platform: MYSQL
    # 在控制台显示执行的sql语句，默认false
    show-sql: true
    # 是否自动生成ddl
    generate-ddl: false
    # 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
    hibernate.ddl-auto: update
    # 方言
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    # 关闭open-in-view配置
    open-in-view: false
    #    hibernate:
    #      naming:
    # 指定jpa的自动表生成策略，驼峰自动映射为下划线格式
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl