# 应用服务 WEB 访问端口
server:
  port: 8080

# spring配置
spring:
  application:
    name: spring-boot-mybatis
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# mybatis配置
mybatis:
  # 给实体类配置别名
  type-aliases-package: com.jourwon.spring.boot.*.entity
  # 加载mybatis核心配置文件
  # configuration 和 configLocation 不能同时存在
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  configuration:
    # 开发环境控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰规则自动映射字段属性值:如字段为user_name的可以映射到userName属性中
    map-underscore-to-camel-case: true
    # 设置sql执行超时时间,以秒为单位的全局sql超时时间设置,当超出了设置的超时时间时,会抛出SQLTimeoutException
    default-statement-timeout: 30
    # 解决查询返回结果含null没有对应字段值问题
    call-setters-on-nulls: true

# pagehelper配置
pagehelper:
  # 分页合理化参数,默认值为false
  reasonable: false
  # 配置方言
  helper-dialect: mysql
  params: count=countSql
  # 默认值为false,当该参数设置为true时,使用 RowBounds 分页会进行 count 查询
  row-bounds-with-count: true
  # 支持通过 Mapper 接口参数来传递分页参数,默认值false
  support-methods-arguments: true