server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #发布确认模式
    publisher-confirm-type: correlated
    #发布退回模式
    publisher-returns: true

